"""add_payment_url

Revision ID: fa2c0417d7e7
Revises: 72cc7211946b
Create Date: 2026-07-02 16:44:57.395095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa2c0417d7e7'
down_revision: Union[str, Sequence[str], None] = '72cc7211946b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('payment_url', sa.String(length=512), nullable=True, comment='URL for Kaspi Pay or other gateway'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'payment_url')
    # ### end Alembic commands ###
